### ISSUE TITLE
LWD instruction

### ISSUE THREAD

**Issue by kosnox** [rjiejie/XuanTie-doc#2]
I have a problem with the LWD instruction. The mnemonic is not compatible with the opcode. Can you explain to me how it should look like correct?

Mnemonic:
lwd rd, imm7(rs1)
opcode:
11100 imm2 rd2 rs1 100 rd1 0001011

**Comment by rjiejie** [comment]
Thanks for your report :)

I checked internal description and 
it should be like the following:

lwd rd1,rd2,(rs1),imm2,3
11100 imm2 rd2 rs1 100 rd1 0001011

**Comment by kosnox** [comment]
ok, thank you for answer ;)
